// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://qpirmryncmugylxwtuyi.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InFwaXJtcnluY211Z3lseHd0dXlpIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzgyNzAxNzIsImV4cCI6MjA1Mzg0NjE3Mn0.9HhQigXauGycxxVwJ015PSNKbj4sa470RCkyndthzkA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);